# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric
minecraft_version=26.3
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.161.0+26.3

# Mod
mod_version=1.8.1
maven_group=com.fabricharvester
archives_base_name=fabric_harvester
